apiVersion: v1
kind: Service
metadata:
  name: hexle-api
  namespace: hexle
  labels:
    app: hexle-api
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.10.116
  selector:
    app: hexle-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
