apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: hexle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
