apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexle-ui
  namespace: hexle
  labels:
    app: hexle-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexle-ui
  template:
    metadata:
      labels:
        app: hexle-ui
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: hexle-ui
          image: unamanic/hexle-ui:5ff059b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: hexle-ui-nginx
