server.port=8080
spring.web.cors.allowed-origins=http://localhost:3000

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
game.ttl.minutes=30

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
